version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "pylint"
        # ignore major version 1.x.x we use for CentOS Linux 6 and 7 where version 2.x.x is not available
        versions: ["1.x.x"]
