version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "pylint"
        # ignore major version 1.x.x we use for CentOS Linux 6 and 7 where
        # version 2.x.x is not available
        versions: ["1.x.x"]

      - dependency-name: "pytest"
        # ignore major version 3.x.x and 4.x.x since we use it for CentOS 6/7
        # and newer versions are not available for these systems
        versions: ["3.x.x", "4.x.x"]

      - dependency-name: "astroid"
        # ignore major version 1.x.x we use for CentOS Linux 6 and 7 where
        # version 2.x.x is not available
        versions: ["1.x.x"]
