specfile_path: packaging/convert2rhel.spec
upstream_package_name: convert2rhel
downstream_package_name: convert2rhel
upstream_project_url: https://github.com/oamg/convert2rhel

srpm_build_deps: []

jobs:
# COPR BUILD JOBS
## COPR build for pull requests
- job: copr_build
  trigger: pull_request
  owner: "@oamg"
  project: convert2rhel
  targets:
  - epel-7-x86_64
  - epel-8-x86_64
  actions:
    # do not get the version from a tag (git describe) but from the spec file
    get-current-version:
    - grep -oP '^Version:\s+\K\S+' packaging/convert2rhel.spec

## COPR build for merge to main branch
- job: copr_build
  trigger: commit
  branch: main
  owner: "@oamg"
  project: convert2rhel
  targets:
  - epel-7-x86_64
  - epel-8-x86_64
  actions:
    # bump spec so we get release starting with 2 and hence all the default branch builds will
    # have higher NVR than all the PR builds
    post-upstream-clone:
    - rpmdev-bumpspec --comment='latest upstream build' ./packaging/convert2rhel.spec
    # do not get the version from a tag (git describe) but from the spec file
    get-current-version:
    - grep -oP '^Version:\s+\K\S+' packaging/convert2rhel.spec

# TEST JOBS
## Tests on pull request stage
- &tests-tier0-destructive-manual
  job: tests
  # Run tests on-demand
  manual_trigger: true
  # Do not merge the PR into the target branch, in case the merge is broken
  # Given we are rebasing the source branches regularly, we do not need this feature enabled
  merge_pr_in_ci: false
  targets:
    epel-7-x86_64:
      distros: [centos-7, oraclelinux-7]
    epel-8-x86_64:
        #TODO bump distro context to 8.7 when the image is available on the testing farm
        # Even though the distro context is 8.6 we are setting the SYSTEM_RELEASE_ENV to 8.7
        # to tag the updated system correctly
      distros: [centos-8-latest, oraclelinux-8.6]
  trigger: pull_request
  identifier: "tier0-destructive"
  tmt_plan: "tier0/destructive"
  # Run on Red Testing Farm Hat Ranch, tag resources to sst_conversions
  use_internal_tf: True
  tf_extra_params:
    environments:
      - settings:
          provisioning:
            tags:
              BusinessUnit: sst_conversions
  labels:
    - tier0
    - tier0-destructive
    - destructive

- &tests-tier0-non-destructive-manual
  <<: *tests-tier0-destructive-manual
  identifier: "tier0-non-destructive"
  tmt_plan: "tier0/non-destructive"
  labels:
    - tier0
    - tier0-non-destructive
    - non-destructive

- &tests-tier1-destructive-manual
  <<: *tests-tier0-destructive-manual
  identifier: "tier1-destructive"
  tmt_plan: "tier1/destructive"
  labels:
    - tier1
    - tier1-destructive
    - destructive

# Disabled for now
#- &tests-tier1-non-destructive-manual
#  <<: *tests-tier0-destructive-manual
#  identifier: "tier1-non-destructive"
#  tmt_plan: "tier1/non-destructive"
#  labels:
#    - tier1-non-destructive
#    - non-destructive

# Tests on merge to main stage
- &tests-tier1
  <<: *tests-tier0-destructive-manual
  # Run test automatically with merge commit to main branch
  manual_trigger: false
  identifier: "tier1"
  tmt_plan: "tier1"
  trigger: commit
  branch: main
