specfile_path: packaging/convert2rhel.spec
upstream_package_name: convert2rhel
downstream_package_name: convert2rhel
upstream_project_url: https://github.com/oamg/convert2rhel

srpm_build_deps: []

jobs:
- job: copr_build
  trigger: pull_request
  owner: "@oamg"
  project: convert2rhel
  targets:
  - epel-6-x86_64
  - epel-7-x86_64
  - epel-8-x86_64
  actions:
    # do not get the version from a tag (git describe) but from the spec file
    get-current-version:
    - grep -oP '^Version:\s+\K\S+' packaging/convert2rhel.spec
- job: copr_build
  trigger: commit
  branch: main
  owner: "@oamg"
  project: convert2rhel
  targets:
  - epel-6-x86_64
  - epel-7-x86_64
  - epel-8-x86_64
  actions:
    # bump spec so we get release starting with 2 and hence all the default branch builds will
    # have higher NVR than all the PR builds
    post-upstream-clone:
    - rpmdev-bumpspec --comment='latest upstream build' ./packaging/convert2rhel.spec
    # do not get the version from a tag (git describe) but from the spec file
    get-current-version:
    - grep -oP '^Version:\s+\K\S+' packaging/convert2rhel.spec
- &tests
  job: tests
  targets:
    epel-7-x86_64:
      distros: [centos-7, oraclelinux-7]
    epel-8-x86_64:
      distros: [centos-8.4, centos-8, oraclelinux-8.4, oraclelinux-8.6]
  use_internal_tf: True
  trigger: pull_request
- <<: *tests
  trigger: commit
  branch: main
