specfile_path: packaging/epel/convert2rhel.spec
upstream_package_name: convert2rhel
downstream_package_name: convert2rhel
upstream_project_url: https://github.com/oamg/convert2rhel

jobs:
- job: copr_build
  metadata:
    owner: "@oamg"
    project: convert2rhel
    targets:
    - epel-6-x86_64
    - epel-7-x86_64
  trigger: pull_request
- job: copr_build
  metadata:
    branch: master
    owner: "@oamg"
    project: convert2rhel
    targets:
    - epel-6-x86_64
    - epel-7-x86_64
  trigger: commit
- job: tests
  metadata:
    targets:
    - epel-6-x86_64
    - epel-7-x86_64
  trigger: pull_request
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
    - el6
    - epel7
