require 'getoptlong'

opts = GetoptLong.new(
  # Native Vagrant options
  [ '--force', '-f', GetoptLong::NO_ARGUMENT ],
  # Custom options
  [ '--convert2rhel-branch', GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--copr-baseurl', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--rhel-repo', GetoptLong::REQUIRED_ARGUMENT ]
)

convert2rhelBranchName='master'
coprBaseURL=''
rhelRepo=''

opts.each do |opt, arg|
  case opt
    when '--convert2rhel-branch'
      convert2rhelBranchName=arg
    when '--copr-baseurl'
      coprBaseURL=arg
    when '--rhel-repo'
      rhelRepo=arg
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "artmello/centos5"
  config.vm.define "convert2rhel-tests"
  config.vm.hostname = "convert2rhel-tests-centos5"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 1
    libvirt.cpu_mode = 'host-passthrough'
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/playbook-major5.yml"
    ansible.become = true
    ansible.compatibility_mode = "2.0"
    ansible.extra_vars = {
      convert2rhel_branch_name: "#{convert2rhelBranchName}",
      copr_baseurl: coprBaseURL,
      rhel_repo: rhelRepo
    }
  end

  config.vm.provision :shell, inline: "convert2rhel --debug --disable-submgr  --disablerepo=*  --enablerepo=rhel -v Server -y"
end
