name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    if: github.actor != 'dependabot' || github.actor != 'pre-commit-ci'
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: "breaking-change,bugfix,documentation,enhancement,security-hardening,no-changelog"
