name: reuse-copr-build@TF

on:
  workflow_call:
    outputs:
      artifacts:
        description: "A string with test artifacts to install in tft test env"
        value: ${{ jobs.reusable_workflow_copr_build_job.outputs.artifacts }}

jobs:
  reusable_workflow_copr_build_job:
    # This job only runs for '/rerun' pull request comments by owner, member, or collaborator of the repo/organization.
    name: Retrieve Copr build id
    runs-on: ubuntu-latest
    outputs:
      artifacts: ${{ steps.gen_artifacts.outputs.artifacts }}
    steps:
      - uses: actions/checkout@v3

      - name: Install necessary deps
        id: deps_install
        run: sudo apt-get install -y libkrb5-dev

      - name: Get latest convert2rhel PR copr build id
        id: get_latest_c2r_copr_build_id
        run: |
          cat << EOF > copr_fedora.conf
          [copr-cli]
          copr_url = https://copr.fedorainfracloud.org
          EOF

          pip install copr-cli
          REGEX='convert2rhel.*${{ github.event.number }}*' _COPR_CONFIG=copr_fedora.conf python ${{ github.workspace }}/scripts/get_copr_build_id.py > build_id
          COPR_ID=$(cat build_id)
          echo "::set-output name=copr_id::${COPR_ID##*/}"

      - name: Generate artifacts output
        id: gen_artifacts
        env:
          ARTIFACTS: ${{ steps.get_latest_c2r_copr_build_id.outputs.copr_id }}
        run: |
          echo "::set-output name=artifacts::${{ env.ARTIFACTS }}"
